stages:
  - sync

sync_to_gitlab:
  stage: sync
  only:
    - master  # 仅在将更改推送到主分支时同步111111
  script:
    - git clone --mirror https://github.com/fengminghui2022/variant-form3-vite-1  # 克隆 GitHub 项目
    - cd repository.git
    - git remote set-url --push master http://139.196.97.162:11033/madapeng/test.git  # 设置推送到 GitLab 仓库
    - git fetch -p master
    - git push --mirror master  # 推送到 GitLab
